### ISSUE TITLE
src/session.ts(241,5): error TS7027: Unreachable code detected.

### ISSUE THREAD

**Issue by kisnalam** [jupyter/jupyter-js-services#102]
C:\Users\IBM_ADMIN\Documents\GitHub\jupyter-js-services>npm install

> jupyter-js-services@0.5.4 prepublish C:\Users\IBM_ADMIN\Documents\GitHub\jupyt
er-js-services
> npm run build

> jupyter-js-services@0.5.4 build C:\Users\IBM_ADMIN\Documents\GitHub\jupyter-js
-services
> npm run build:src && npm run build:test

> jupyter-js-services@0.5.4 build:src C:\Users\IBM_ADMIN\Documents\GitHub\jupyte
r-js-services
> tsc --project src

src/session.ts(241,5): error TS7027: Unreachable code detected.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build:src"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! jupyter-js-services@0.5.4 build:src: `tsc --project src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyter-js-services@0.5.4 build:src script 'tsc --project
 src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyter-js-services p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc --project src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyter-js-services
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyter-js-services
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IBM_ADMIN\Documents\GitHub\jupyter-js-services\npm-debug.l
og

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! jupyter-js-services@0.5.4 build: `npm run build:src && npm run build:te
st`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyter-js-services@0.5.4 build script 'npm run build:src
 && npm run build:test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyter-js-services p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:src && npm run build:test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyter-js-services
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyter-js-services
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IBM_ADMIN\Documents\GitHub\jupyter-js-services\npm-debug.l
og

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! jupyter-js-services@0.5.4 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyter-js-services@0.5.4 prepublish script 'npm run buil
d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyter-js-services p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyter-js-services
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyter-js-services
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IBM_ADMIN\Documents\GitHub\jupyter-js-services\npm-debug.l
og

my node version:
C:\Users\IBM_ADMIN\Documents\GitHub\jupyter-js-services>node -v
v5.7.1
C:\Users\IBM_ADMIN\Documents\GitHub\jupyter-js-services>npm -v
3.6.0

**Comment by blink1073** [comment]
Thanks @kisnalam, I had not yet used TypeScript 1.8 on this project, see #103 for the fix.

**Comment by blink1073** [comment]
I just released `jupyter-js-services@0.5.5` with the patch.

**Comment by jasongrout** [comment]
For the record, it seems that TS 1.8 solves similar problems: https://github.com/Microsoft/TypeScript/issues/1613#issuecomment-163122205

**Comment by jasongrout** [comment]
A more relevant issue: https://github.com/Microsoft/TypeScript/issues/7588
