### ISSUE TITLE
sendShellMessage named deceptively

### ISSUE THREAD

**Issue by jdfreder** [jupyter/jupyter-js-services#104]
I can't tell, should this method of Kernel actually be named `sendMessage`?  From what I can tell it sends any type of message.  In fact, there's a top level function in the kernel.ts file called `sendKernelMessage` which uses `sendShellMessage`.  I think one of these two should be renamed.  

Also, side question, is there any way to listen to all messages received by `kernel._ws` without explicitly accessing `kernel._ws`?

**Comment by blink1073** [comment]
Closing based on discussion on appear.in, we have the ability to send messages to `shell` and `stdin` already.  Also note that you can override `window.WebSocket` if you wanted a custom implementation (we override `global.WebSocket` in the mocha tests).

**Comment by jdfreder** [comment]
Thanks @blink1073 !
