### ISSUE TITLE
Set the contentType for ajaxRequest

### ISSUE THREAD

**Issue by parente** [jupyter/jupyter-js-services#123]
Example: The POST request to /api/kernels currently has `Content-Type: text/plain`. This is not a problem for the notebook server which does not care, but becomes problematic for alternative backends (dashboard server) that want deal with requests according to content type (express body parser).

Probably should be done throughout. I believe all of the RESTful endpoints take JSON.

**Comment by blink1073** [comment]
Thanks for the heads up!  See #125.
