### ISSUE TITLE
Not able to inject http request headers into client.js

### ISSUE THREAD

**Issue by dockter-84** [jupyter/jupyter-js-services#132]
Using the demo node client.py  (https://github.com/jupyter/kernel_gateway_demos/blob/master/node_client_example/client.js) as a base,  the introduction of http request headers does not seem to actually send the headers. 

Here's the modifed code.  To see the modifications, search for "ajaxSettings":

```javascript
// Copyright (c) Jupyter Development Team.
// Distributed under the terms of the Modified BSD License.

var xmlhttprequest = require('xmlhttprequest');
var ws = require('ws');

global.XMLHttpRequest = xmlhttprequest.XMLHttpRequest;
global.WebSocket = ws;

var jupyter = require('jupyter-js-services');

var kg_host = process.env.GATEWAY_HOST || '192.168.99.100:8888';

var ajaxSettings = {
    user: 'test-user',
    password: 'test-password',
    requestHeaders: {
        'X-Spark-service-instance-id': 'test-instance-id'
    }
}

// get info about the available kernels and start a new one
jupyter.getKernelSpecs('http://'+kg_host).then((kernelSpecs) => {
    console.log('Available kernelspecs:', kernelSpecs);
    var options = {
        baseUrl: 'http://'+kg_host,
        wsUrl: 'ws://'+kg_host,
        ajaxSettings: ajaxSettings,
        name: kernelSpecs.default
    };
    // request a kernel in the default language (python)
    jupyter.startNewKernel(options).then((kernel) => {
        // execute some code
        var future = kernel.execute({ code: 'print("Hello world!")' } );
        future.onDone = () => {
            // quit when done
            process.exit(0);
        };
        future.onIOPub = (msg) => {
            // print received messages
            console.log('Received message type:', msg.msg_type);
            if(msg.msg_type === 'stream') {
                console.log('  Content:', msg.content.text);
            }
        };
    });
});
```

**Comment by blink1073** [comment]
Hi @dockter-84, would you mind setting a break point here: https://github.com/jupyter/jupyter-js-utils/blob/master/src/index.ts#L269 and seeing if that value is getting propagated through line 271 properly?

**Comment by dockter-84** [comment]
@blink1073   I can't find the "index.ts" where I'm running the code.  (I'm somewhat new to node.)    Are you not able to reproduce the error with the slight modification to the existing client.js?

**Comment by blink1073** [comment]
I ran your code by making the changes listed below and got the following output:

<img width="413" alt="screen shot 2016-04-16 at 7 34 10 am" src="https://cloud.githubusercontent.com/assets/2096628/14580985/22483722-03a6-11e6-9ea5-a0218352a87d.png">

To get there:
1) Edit the code to add a debug point before the call to `startKernel` by adding the line `debugger`.
2) Run the code
3) Launch node-inspector
4) Ran to the `debugger` line
5) Set a debug point in `jupyter-js-utils/lib/index` (see screen shot)
6) Ran to that line
7) Inspected the outputs

<img width="834" alt="screen shot 2016-04-16 at 7 36 28 am" src="https://cloud.githubusercontent.com/assets/2096628/14581006/7736b79a-03a6-11e6-95ed-7ab259b2682a.png">
 
This video gives a good intro: https://www.youtube.com/watch?v=03qGA-GJXjI

To your original question, I haven't used `kernel_gateway` yet, I'll try the actual example on Monday.

**Comment by blink1073** [comment]
Okay, I got the demo working, but it was using an old version of `jupyter-js-services`.  Please try running `npm install --save jupyter-js-services@latest` and then running the code again.  If that still does not work, please see the updated instructions above.

**Comment by dockter-84** [comment]
I ran the following:

```console
rm -rf ~/kernel_gateway_demos
cd ~
git clone https://github.com/jupyter-incubator/kernel_gateway_demos.git
cd ~/kernel_gateway_demos/node_client_example
npm install
export GATEWAY_HOST=dev.spark.bluemix.net:8000/jupyter/v1
node ~/kernel_gateway_demos/node_client_example/client.js
```
...and it didn't even reach the webserver.   Do you get the same result?

**Comment by blink1073** [comment]
I do not have a spark setup, but I was able to reach the webserver using a local gateway.

**Comment by blink1073** [comment]
What is the output of your `jupyter kernelgateway` terminal command?

**Comment by dockter-84** [comment]
It immediately came back without any output.

**Comment by blink1073** [comment]
As in, you ran `$ jupyter kernelgateway` and the command immediately exits with no output?  What other options are you passing?

**Comment by dockter-84** [comment]
Sorry,  I updated my comment to say client.py came back empty.   `$ jupyter kernelgateway` is buried within a system, to I need to do some digging.   But the issue is that the client didn't even get to the webserver.

**Comment by blink1073** [comment]
I'd recommend using `node-inspector` on the client.py script then: https://github.com/jupyter/jupyter-js-services/issues/132#issuecomment-210806682.

**Comment by dockter-84** [comment]
The real test is whether the HTTP headers are making it to the receiving webserver?   Have you tested this?

**Comment by blink1073** [comment]
Closing in favor of https://github.com/jupyter/kernel_gateway_demos/issues/13.
