### ISSUE TITLE
"use strict" tag should be inside function

### ISSUE THREAD

**Issue by episodeyang** [jupyter/jupyter-js-services#15]
Hi, 

The "use strict" tag should be placed inside functions. This is to prevent the tag from breaking other javascript files when the files are concatenated together.

**Comment by blink1073** [comment]
Hi @episodeyang, we are not intending for these files to be concatenated.  They are released as a node package, which is intended to be run through browserify.  This results in a "use strict" tag per file (module), which is our intended effect.

**Comment by blink1073** [comment]
Closing issue, feel free to reopen if you disagree.

**Comment by episodeyang** [comment]
No worries, that works!
