### ISSUE TITLE
Way to use the scripts as stand-alone library

### ISSUE THREAD

**Issue by episodeyang** [jupyter/jupyter-js-services#16]
Thanks for this great repo! 

Would it be possible to build the script such that the compiled javascript file can be used as a stand alone library on the client side?

Best,
Ge

**Comment by rgbkrk** [comment]
Client meaning frontend I presume?

While not currently in this `package.json`, we can create a browserified version of the javascript:

```
$ npm install -g browserify
$ mkdir dist
$ browserify lib/index.js --outfile dist/services.js --standalone services
$ ls dist
services.js
```

Because we're using commonjs here from node land though, you can re-package for webpack, requirejs, etc.

Where would you be using this?

**Comment by episodeyang** [comment]
I actually ended up writing my own last night! I am using my own notebook for my research at the moment, and I wanted to be able to run some python script from the text editing area. 

In the future though, it would make more sense to have this repo being the official client-side javascript library for ipython, so that other projects can just use it. It is also nice because it will be kept up to-date. Granted the 5.0 protocol is already stable so it shouldn't need to be changes all the time.

**Comment by hedata** [comment]
hi guys trying out the services js as a standalone part but running into some troubles.

when already having loaded the services.js
and i have a jupyter notebook server on 8888 running acceptinig connections from everywhere.
```
var sessionOptionsTest = {
  notebookPath: "test.ipynb",
  kernelName: "python3",
  baseUrl: "/localtest/",
  wsUrl: "ws://localhost:8888"
}
var sessionTest = new services.NotebookSession(sessionOptionsTest);
sessionTest.start()
```
then a kernel is started but when trying to connect to the websocket the jupyter notebook gives a 404 error. when i look into the headers i find that:
```
ws://.../api/kernel/e2c60ccc-d809-4a16-990e-7968cedbf411/channels?session_id=6FB78E54322240AA8FE656629E1DCF66 
```
in the api description the path should be kernels ; when i change the var KERNEL_SERVICE_URL = 'api/kernel'; in your code to kernels then i get the connection started but half a second later i get disconnected again and the jupyter notebook throws me an interesting error:

```
Uncaught exception in /localtest/api/kernels/034a67b2-8496-4a3b-a8d2-427eff8b5386/channels
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 415, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/notebook/services/kernels/handlers.py", line 250, in on_message
        self.session.send(stream, msg)
      File "/usr/local/lib/python3.4/dist-packages/jupyter_client/session.py", line 665, in send
        to_send = self.serialize(msg, ident)
      File "/usr/local/lib/python3.4/dist-packages/jupyter_client/session.py", line 579, in serialize
        self.pack(msg['parent_header']),
    KeyError: 'parent_header'
```

help would be appreciated :-)

**Comment by blink1073** [comment]
Hi @hedata, this library is still a work in progress, but thank you for the feedback.  We are currently refactoring the Kernel and the Session in #20, but I will try your example before we merge it.

**Comment by blink1073** [comment]
Hi @hedata, you should be able to run the code in the Readme to create a notebook session now.

**Comment by blink1073** [comment]
I'm calling this one complete, since we have working integration tests, feel free to reopen @episodeyang.

**Comment by episodeyang** [comment]
@blink1073 Thanks for the work! I guess the decision to write my own bought me about a month and half:)
