### ISSUE TITLE
Make a single .js file that can be included in other projects

### ISSUE THREAD

**Issue by tkw1536** [jupyter/jupyter-js-services#160]
We would like to use the jupyter-js-services library, however it would be very complicated to include an ```npm build``` style workflow into our project. 

It would be great if there was a single ```jupyter-js-services.js``` that file that we could just include into our html page without having to include additional libraries. Something like [webpack](https://webpack.github.io/) or [browserify](http://browserify.org/) can do this. If we do this on our end, it means a significant effort every time we want to update to the newest version, so we were hoping that you could generate single such a file somewhere in this repository. 

/cc @florian-rabe @minrk

**Comment by SylvainCorlay** [comment]
@blink1073 it would make sense to have a build-step ahead as part of pre-publish like we do for `jupyter-js-widgets`, another benefit is that it would be immediately served by npmcdn.

**Comment by blink1073** [comment]
Awesome, thanks for the pointer @SylvainCorlay, I'll copy what you did there.
