### ISSUE TITLE
Document promise polyfill needed for IE

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter-js-services#163]
If the user wants things to work on IE 11, they need a promise polyfill, such as es6-promise. This should be documented somewhere.

(Inspired from https://github.com/sagemath/sagecell/issues/466).

**Comment by willingc** [comment]
@jasongrout Do you think this would be better here or in jupyterlab documentation?

If here, at end of README or a new technical-note.md?

**Comment by blink1073** [comment]
cf https://github.com/jupyter/jupyter-js-services/pull/167
