### ISSUE TITLE
cache kernelinfo

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter-js-services#209]
In https://github.com/jupyter/jupyter-js-services/blob/fc0e0467c1f573582e7ef9432f351682dbe0b67b/src/kernel.ts#L707, a request is made every time the info is requested. Since it is unlikely to change (and indeed, we don't provide any change signals for it anyway), we should cache it. What about having a new attribute like `.info` that is a promise for the info, and either fetches or resolves to the cached value. That way someone can still fetch new info to refresh the cache, but most users will probably just use the cached value.

cf. https://github.com/jupyter/jupyterlab/issues/520

**Comment by blink1073** [comment]
We are using a kernel_info request to verify a reconnect or a restart.

**Comment by jasongrout** [comment]
Even more of a reason to cache the info. For example, the notebook just needs to get some info out for the language settings. That shouldn't need to request the info again.

**Comment by blink1073** [comment]
Yeah, we can just explicitly clear the cache on reconnect or restart.

**Comment by jasongrout** [comment]
Yes, good point.

**Comment by jasongrout** [comment]
or just keep doing the kernelinfo call and refresh the cache.

**Comment by blink1073** [comment]
The public call should always use the cache, we can either clear the cache or call a private kernel info method.

**Comment by blink1073** [comment]
(With a note about this behavior in the docstring).

**Comment by jasongrout** [comment]
I wasn't sure if there were valid reasons for actually requesting the message be sent from a public call, and how closely we should make sure the objects mirror the actual messages that could be sent. That's why I suggested keeping the call public. But I'm okay with the message sending being private too.

**Comment by blink1073** [comment]
Ah, I see what you mean, have a cached `kernelInfo` and a `getKernelInfo` method.  Yeah, I like that better.
