### ISSUE TITLE
connectToSession by id does not populate missing session options

### ISSUE THREAD

**Issue by nikitakit** [jupyter/jupyter-js-services#214]
I'd like to be able to connect to an existing session using only the session ID and the server URL. The docs suggest that `connectToSession(id, {"baseUrl":"http://localhost:8888"})` should work, which it mostly does. Functionality like running commands works great.

However, the resulting session object is missing certain attributes, for example `path`. I think these attributes should be populated automatically from the server whenever a session is connected, instead of making them mandatory in the call to `connectToSession`.

I can work around this by separately fetching the session model and then calling `session.update`, but I don't believe that this is the intended approach.

**Comment by blink1073** [comment]
Hi @nikitakit, nice catch!  See #215 for the fix.  `path` was the only part of the `ISession.IModel` that we weren't using.

**Comment by nikitakit** [comment]
Thanks!

**Comment by blink1073** [comment]
Released as v0.18.1.
