### ISSUE TITLE
File extension only lowercase

### ISSUE THREAD

**Issue by dhuebner** [jupyter/jupyter-js-services#217]
I have a question regarding the ContentsManager#normalizeExtension in /jupyter-js-services/src/contents.ts 

What is the reason to lowercase the file extension?

There are languages where the Upper case is also common as a default file extension. IMHO it should be API-user decision that provides the extension for ICreateOptions

**Comment by blink1073** [comment]
Hi @dhuebner, agreed that the lower-casing behavior should not be in jupyter-js-services.  We were using it from the DocumentRegistry in JupyterLab.  If anything, that behavior should be moved there.

**Comment by blink1073** [comment]
Hi @dhuebner, yes, I will circle back to this after I finish my current PR on JupyterLab (it is a bit of a bear).

**Comment by blink1073** [comment]
@dhuebner, fixed in v0.19.0.

**Comment by dhuebner** [comment]
@blink1073 Cool. Thanks a lot!
