### ISSUE TITLE
Provide a server extension instead of mock server objects

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-services#229]
- We can use a server extension that provides a contents manager that uses a mock file system, similar to the [labextension tests](https://github.com/jupyter/jupyterlab/blob/master/jupyterlab/tests/test_labextensions.py).  
- We could add a few other custom capabilities as needed.
- This would make it transparent to test objects that use jupyter-js-services.
- We would use a similar script to the [integration test](https://github.com/jupyter/jupyter-js-services/blob/master/test/integration_test.py) to bootstrap the Jupyter server and the karma server.
- The local unit tests would still use `ws` and `sinon` for testing, because we need to simulate bad responses from the server.

@jasongrout, @minrk, thoughts on this approach?

**Comment by minrk** [comment]
Sounds like a great idea! How exactly do you 'provide' it, since this is a js package and that would be Python?

Aside: you don't need to use the serverextension mechanism to register a ContentsManager, a single line of config would suffice `NotebookApp.contents_manager_class = 'package'`.

**Comment by blink1073** [comment]
Great, even easier!  We could make this a hybrid python and JS library library like we've been doing with JupyterLab + friends.
