### ISSUE TITLE
Allow xhr options to be passed (e.g., withCredentials)

### ISSUE THREAD

**Issue by parente** [jupyter/jupyter-js-services#31]
Currently, XHR calls such as the one here (https://github.com/jupyter/jupyter-js-services/blob/master/src/kernel.ts#L105) and in jupyter/notebook do not allow the caller to specify additional XHR options. If I want to run my kernel provider (e.g., tmpnb) behind a proxy that, for example, requires auth headers to be sent along with XHR requests, I have to hack the code to set the withCredentials flag.  Likewise, if I have a setup in which I need to send additional headers, I have to hack the code. It would be nice if these comm options could be set via args to the functions.

Related: oreillymedia/thebe#52

**Comment by blink1073** [comment]
Is the `withCredentials` flag the only thing you need, or would you also need to provide headers to `setRequestHeader`?

**Comment by parente** [comment]
withCredentials is just one need we've hit so far. I suspect as well that, depending on the deployment scenario, headers might be another. Beyond that, I'm not sure. There could always be more, but it's certainly hard to plan for them all up-front short of exposing the entire XHR and Websocket APIs.

**Comment by blink1073** [comment]
We could allow a second optional argument to the XHR calls with this signature:

```typescript
interface IAjaxOptions {
  timeout?: number;
  ontimeout?: (evt: Event) => {};
  requestHeaders?: { [key: string]: string; };
  withCredentials?: boolean;
}
```

**Comment by parente** [comment]
A second arg makes sense. As long as it can grow new options over time (e.g., https://xhr.spec.whatwg.org/#the-open()-method supports username, password too, and maybe some use case will need those too)

The set of attrs you have right now seems fine as a starter.

**Comment by blink1073** [comment]
Yep, we can add as many as needed, I added those two above.

**Comment by sccolbert** [comment]
+1 except for the `ontimeout` callback. I think the promise should just be rejected if the xhr times out.

**Comment by blink1073** [comment]
Works for me.

**Comment by blink1073** [comment]
Does it make sense for this to be a property on each class?  I think it would be a lot cleaner than adding optional arguments to all of the methods, but that must be weighed against whether these values are expected to differ between methods.

**Comment by minrk** [comment]
Some are likely to be consistent across all methods for a given instance (e.g. auth headers), others are likely to be consistent within a given method, and others are likely to be passed on a per-call basis.

**Comment by blink1073** [comment]
Okay, so let's just standardize on per-call then.

**Comment by minrk** [comment]
I think that's a good starting point since it covers all bases, and we can add instance-wide defaults if we encounter something where it starts to get annoying passing the same key all the time. This is likely to show up when we add token-based auth, which we don't have, yet.

**Comment by blink1073** [comment]
Got it, thanks.
