### ISSUE TITLE
Installing via npm produces deprecation warnings

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/jupyter-js-services#321]
```
yuvipanda@courage:~/code/stresshub$ npm install --save jupyter-js-services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
+ jupyter-js-services@0.21.1
added 8 packages in 1.675s
```

Would be nice if it didn't produce a deprecation warning :)

**Comment by blink1073** [comment]
Hi @yuvipanda, this repo is deprecated, moved to https://github.com/jupyterlab/jupyterlab/tree/master/packages/services.

**Comment by yuvipanda** [comment]
I see. Someone should update https://www.npmjs.com/package/jupyter-js-services to point to that?

**Comment by blink1073** [comment]
Good call, done.
