### ISSUE TITLE
KernelFutureHandler shouldn't rely on a specific order of incoming messages.

### ISSUE THREAD

**Issue by bpburns** [jupyter/jupyter-js-services#44]
I have a scenario where I'm sending code to execute on a scala kernel (a simple "1 + 1") however the result never makes it back to the KernelFutureHandler.  In kernel.ts, _handleIOPub (https://github.com/jupyter/jupyter-js-services/blob/master/src/kernel.ts#L1119), The _handleDone routine is called if a status of idle and reply messages have been received.  In my scenario the results comes back after these two messages.  At that point the kernel future handler has been removed.  I've attached a print out of the messages received from onWSMessage that shows the order of the messages.  This is the result of calling startNewKernel followed by executing the code 1 + 1.  The last message ends up in undhandledMessage instead of onIOPub in the kernel future handler.

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: 'e93cfe6b-fbf5-4077-8d8b-976c86397def',
     username: 'root',
     msg_type: 'status',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { execution_state: 'busy' },
  msg_id: 'e93cfe6b-fbf5-4077-8d8b-976c86397def',
  channel: 'iopub',
  msg_type: 'status',
  parent_header: 
   { version: '5.0',
     msg_id: '708bf828-34f0-4101-9c61-a6165431a045',
     username: 'username',
     msg_type: 'kernel_info_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916660856' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: 'a558a80d-8e18-4899-ab34-12ea24f9e475',
     username: 'root',
     msg_type: 'status',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { execution_state: 'idle' },
  msg_id: 'a558a80d-8e18-4899-ab34-12ea24f9e475',
  channel: 'iopub',
  msg_type: 'status',
  parent_header: 
   { version: '5.0',
     msg_id: '708bf828-34f0-4101-9c61-a6165431a045',
     username: 'username',
     msg_type: 'kernel_info_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916660863' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: 'b7709baf-ec00-4067-be3b-3f67e6d50fb8',
     username: 'root',
     msg_type: 'status',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { execution_state: 'busy' },
  msg_id: 'b7709baf-ec00-4067-be3b-3f67e6d50fb8',
  channel: 'iopub',
  msg_type: 'status',
  parent_header: 
   { version: '5.0',
     msg_id: 'ba9b81390772dd2a44bfe2a2cf33e733',
     username: '',
     msg_type: 'kernel_info_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916660869' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: '4cb5cfb5-93fd-43c0-8d7b-c9edb106b482',
     username: 'root',
     msg_type: 'status',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { execution_state: 'idle' },
  msg_id: '4cb5cfb5-93fd-43c0-8d7b-c9edb106b482',
  channel: 'iopub',
  msg_type: 'status',
  parent_header: 
   { version: '5.0',
     msg_id: 'ba9b81390772dd2a44bfe2a2cf33e733',
     username: '',
     msg_type: 'kernel_info_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916660880' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: '346190fe-f631-4a01-9e80-325b4df19fa6',
     username: '',
     msg_type: 'kernel_info_reply',
     session: '865e257e-6244-4da0-a076-5f2563d077d9' },
  content: 
   { banner: 'IBM Spark Kernel',
     language_info: { name: 'scala' },
     implementation_version: '0.1.5-SNAPSHOT',
     implementation: 'spark',
     protocol_version: '5.0',
     language_version: '2.10.4' },
  msg_id: '346190fe-f631-4a01-9e80-325b4df19fa6',
  channel: 'shell',
  msg_type: 'kernel_info_reply',
  parent_header: 
   { version: '5.0',
     msg_id: 'ba9b81390772dd2a44bfe2a2cf33e733',
     username: '',
     msg_type: 'kernel_info_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916660877' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: '92618f0c-a6a8-4aa4-8203-73a9334884e8',
     username: 'root',
     msg_type: 'status',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { execution_state: 'busy' },
  msg_id: '92618f0c-a6a8-4aa4-8203-73a9334884e8',
  channel: 'iopub',
  msg_type: 'status',
  parent_header: 
   { version: '5.0',
     msg_id: 'b079deeb86709bbba2baa35d1848e596',
     username: '',
     msg_type: 'execute_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916660893' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: '8137309d-e9aa-4ba9-9798-fa47ba60f396',
     username: 'root',
     msg_type: 'execute_input',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { code: '1 + 1', execution_count: 1 },
  msg_id: '8137309d-e9aa-4ba9-9798-fa47ba60f396',
  channel: 'iopub',
  msg_type: 'execute_input',
  parent_header: 
   { version: '5.0',
     msg_id: 'b079deeb86709bbba2baa35d1848e596',
     username: '',
     msg_type: 'execute_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916660937' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: '90ab3839-5c6c-4e01-8636-ea007c72d31a',
     username: 'root',
     msg_type: 'status',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { execution_state: 'idle' },
  msg_id: '90ab3839-5c6c-4e01-8636-ea007c72d31a',
  channel: 'iopub',
  msg_type: 'status',
  parent_header: 
   { version: '5.0',
     msg_id: 'b079deeb86709bbba2baa35d1848e596',
     username: '',
     msg_type: 'execute_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916661287' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: 'e878c505-a2bd-416b-adbe-107aea6b8e04',
     username: 'root',
     msg_type: 'execute_reply',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: 
   { status: 'ok',
     user_expressions: {},
     payload: [],
     execution_count: 1 },
  msg_id: 'e878c505-a2bd-416b-adbe-107aea6b8e04',
  channel: 'shell',
  msg_type: 'execute_reply',
  parent_header: 
   { version: '5.0',
     msg_id: 'b079deeb86709bbba2baa35d1848e596',
     username: '',
     msg_type: 'execute_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916661301' },
  buffers: [] }

_onWSMessage
{ header: 
   { version: '5.0',
     msg_id: 'ae6592b0-2f68-47ed-8980-b4883f907f9e',
     username: 'root',
     msg_type: 'execute_result',
     session: 'dd7e1080-86d0-421a-a7a7-b2436737fb3e' },
  content: { data: { 'text/plain': '2' }, metadata: {}, execution_count: 1 },
  msg_id: 'ae6592b0-2f68-47ed-8980-b4883f907f9e',
  channel: 'iopub',
  msg_type: 'execute_result',
  parent_header: 
   { version: '5.0',
     msg_id: 'b079deeb86709bbba2baa35d1848e596',
     username: '',
     msg_type: 'execute_request',
     session: 'c5f7fa052b21afa1acc047d392cf30fa' },
  metadata: { timestamp: '1444916661311' },
  buffers: [] }

**Comment by minrk** [comment]
If the results of an execution come back after status-idle, the message spec is being violated. status-idle indicates that the execution is complete, and all outputs have been sent. Otherwise, it is impossible to know if/when output will ever complete, and every execution will have to remain in the mapping for output callbacks for the lifetime of the kernel, growing unbounded in memory, and no promise can ever resolve.

**Comment by parente** [comment]
Does the messaging spec state that as a MUST somewhere? I'm looking at the page here http://jupyter-client.readthedocs.org/en/latest/messaging.html but I might be missing it. If it's a strict requirement, we should definitely call that out.

**Comment by minrk** [comment]
I think we'll have to be careful what language we use. It's possible for output to be sent outside the status:busy-idle window (e.g. background threads in Python), but these shall be considered orphaned. The notebook application, for instance, will likely preserve its current behavior by registering a handler on the unhandledMessage event, to do what it currently does: associate orphaned output with the 'current' cell. Alternately, it could maintain a mapping of cell:msg_id, which is bounded by the number of cells, and doesn't suffer from unbounded memory problems. But we cannot do this with a Future interface, because then it is impossible for futures to ever resolve.

Another change we could consider here is to decouple resolving the Future, which indicates that execution has completed, from cleaning up the output handlers, which is the source of the unbounded growth. If we rely on the caller to decide when outputs *may not* arrive anymore, that might make things like the notebook's current behavior easier to implement.

**Comment by minrk** [comment]
I opened #45 which should make it easier for callers to take over disposal if they want to handle messages arriving at a later point. It should make it easier for things like the notebook to do what it wants, which is to keep callbacks registered for each cell, and dispose of those futures when a new execution is requested or output is cleared, since this is bounded comfortably by the number of cells on the page.

**Comment by KimStebel** [comment]
This would also be an issue with the node.js kernel, which can also return a result before the last output is sent.

**Comment by blink1073** [comment]
I'm calling this one fixed by #45.
