### ISSUE TITLE
npm install doesn't fetch any of the source code

### ISSUE THREAD

**Issue by doronrosenberg** [jupyter/jupyter-js-services#48]
Doing a npm install jupyter-js-services is not pulling the source, all I get is:

Dorons-MacBook-Pro:jupyter-js-services doronrosenberg$ ls -la
drwxr-xr-x   7 doronrosenberg  staff      238 Oct 26 11:16 .
drwxr-xr-x  10 doronrosenberg  staff      340 Oct 26 11:15 ..
-rw-r--r--   1 doronrosenberg  staff     1493 Oct 26 11:15 LICENSE
-rw-r--r--   1 doronrosenberg  staff     8486 Oct 26 11:15 README.md
drwxr-xr-x  20 doronrosenberg  staff      680 Oct 26 11:16 node_modules
-rw-r--r--   1 doronrosenberg  staff    11089 Oct 26 11:15 package.json

Not sure why this is happening perhaps because there are no release?

**Comment by blink1073** [comment]
We have not officially released on `npm` as of yet.  The released version will have the compiled source code in the `/lib` folder.

**Comment by doronrosenberg** [comment]
I also tried using this in package.json:

"jupyter-js-services": "git+https://git@github.com/jupyter/jupyter-js-services.git",

and had the same issue.  Is there a working way currently to include it as a npm dependency?

**Comment by blink1073** [comment]
We would have to check the `/lib` files into the repository, which we could do until we release it on npm, what do you think @minrk?

**Comment by doronrosenberg** [comment]
@blink1073 what is confusing me is that the ```src/``` dir isn't being fetched by npm so I can't even just do a postInstall to build the ts files.

**Comment by blink1073** [comment]
@doronrosenberg, we are explicitly only including files in `/lib` on npm (once published): https://github.com/jupyter/jupyter-js-services/blob/master/package.json#L51

**Comment by minrk** [comment]
@blink1073 is it not possible to run a build step as part of install from a repo? I would assume there has to be, if it were any language other than Javascript. I don't think we should start tracking generated files in the repo. We can start publishing incomplete releases as 0.0.1, etc. now-ish if there's no decent way to test this out from git.

**Comment by blink1073** [comment]
We would have to include `src/` in `package.json`, and add `npm run build` as a `postinstall` script, and then switch that out when we decided to publish.  We'd also have to make TypeScript a hard dependency instead of a `devDependency`.  I'd prefer to wait until #47 is merged, and then go with standard npm releases.

**Comment by minrk** [comment]
Yikes. Let's definitely go with standard releases, then.

**Comment by blink1073** [comment]
Ready to roll @doronrosenberg: https://www.npmjs.com/package/jupyter-js-services.
