### ISSUE TITLE
Connecting to local Jupyter Notebook results in Cross Origin error

### ISSUE THREAD

**Issue by doronrosenberg** [jupyter/jupyter-js-services#51]
I have a Node.js project using Jupyter JS Services and a Jupyter Notebook running locally on 127.0.0.1 on OSX.

The baseUrl being passed into startNewKernel is `http://127.0.0.1:8888`. The error I get on the Notebook side is:
```
Blocking Cross Origin WebSocket Attempt.  Origin: 127.0.0.1:8888, Host: 127.0.0.1:8888
```
This seems to happen in the Notebook code because `https://` is missing from the Origin header (the python code uses urlparse().netloc which only works if there is a protocol it seems) - it works if I change the websocket creation code (Kernel.js) to this:
```
new WebSocket(url, {headers: {Origin: this._baseUrl}});
```
Is this expected behavior?  I can work around it by launching the Notebook with `--NotebookApp.allow_origin="*"` as running it locally is not production but its an odd issue.

**Comment by minrk** [comment]
I'll have to read some docs, but this seems like a bug in the node.js websocket library, setting an invalid Origin header. As far as I can tell, [it is not valid](https://tools.ietf.org/id/draft-abarth-origin-03.html#serialization) to have an Origin that does not start with `proto://`.

**Comment by minrk** [comment]
@doronrosenberg actually, can you provide some more context and sample code? When I run this, it works fine without any allow_origin config.

**Comment by doronrosenberg** [comment]
@minrk So looks like this was happening because I was using an older WS version (bah!) - this was fixed as part of https://github.com/websockets/ws/commit/e718f47da83ee950bbfc18ea05a1a3554b3cb89e.  The WS library now no longer creates a default Origin header - it only creates one if you specify one.

I am not sure how this will affect production and if we need the Origin header down the road - this might affect browser users since they can't specify the header value (or CORS) using jupyter-js-services if they want to do cross-domain calls.

**Comment by minrk** [comment]
cross-domain is already handled by the CORS config of the server, so browsers shouldn't be an issue. The default behavior is as it should be.
