### ISSUE TITLE
ajaxRequest should warn on invalid/undefined `settings.methods`

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-js-services#57]
And generally I would have expected the API to be closer to $.ajax the setting/option distinction is bit annoying to refactor when we already have layers of call in JS. 

Here I was caught by GET not being the default.

**Comment by minrk** [comment]
Good point, and GET should indeed be the default at the base level.

**Comment by blink1073** [comment]
@Carreau, how about this interface (only one object):

```
/**
 * Input settings for an AJAX request.
 */
export
interface IAjaxSettings {
  /**
   * The HTTP method to use (defaults to "GET").
   */
  method?: string;

  /**
   * The return data type (used to parse the return data).
   */
  dataType?: string;

  /**
   * The outgoing content type, used to set the `Content-Type` header.
   */
  contentType?: string;

  /**
   * The request data.
   */
  data?: any;

  /**
   * The number of milliseconds a request can take before automatically
   * being terminated.  A value of 0 (which is the default) means there is
   * no timeout.
   */
  timeout?: number;

  /**
   * A mapping of request headers, used via `setRequestHeader`.
   */
  requestHeaders?: { [key: string]: string; };

  /**
   * Is a Boolean that indicates whether or not cross-site Access-Control
   * requests should be made using credentials such as cookies or
   * authorization headers.  Defaults to `false`.
   */
  withCredentials?: boolean;

  /**
   * The user name associated with the request.  Defaults to `undefined`.
   */
  user?: string;

  /**
   * The password associated with the request.  Defaults to `undefined`.
   */
  password?: string;
}


/**
 * Asynchronous XMLHTTPRequest handler.
 *
 * Based on this [example](http://www.html5rocks.com/en/tutorials/es6/promises/#toc-promisifying-xmlhttprequest).
 */
export
function ajaxRequest(url: string, settings: IAjaxSettings): Promise<any>;
```

**Comment by blink1073** [comment]
That uses the official names and defaults from the `XHR` interface except for `dataType`, `contentType`, and `requestHeaders`.

**Comment by Carreau** [comment]
I'll have a look tomorrow. 
Thanks !

**Comment by blink1073** [comment]
ping @Carreau, I'd like to implement this and add `cache` at the same time.

**Comment by Carreau** [comment]
Sorry slips through the crack. Putting that on top of TODO list.

**Comment by Carreau** [comment]
That seem fine, though I haven't re-played with that in a while, so it's hard to tell. 
Feel free to move forward I'll complain later if I need to.

**Comment by blink1073** [comment]
Great, that sounds good, thanks.

**Comment by Carreau** [comment]
In general don't wait for me on things like that, I'm still highly busy with maintaining notebook and IPython for now. I'll probably be more involved once there actually some work in bringing phosphide/phosophor closer to the main notebook repo.
