### ISSUE TITLE
Use the full message in the Comm methods instead of just the data

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-services#64]

**Comment by blink1073** [comment]
@jdfreder, any objection to this?

**Comment by blink1073** [comment]
This would have the full message instead of just data: https://github.com/jupyter/jupyter-js-services/blob/master/src/ikernel.ts#L761

**Comment by blink1073** [comment]
So would `onClose` for consistency.

**Comment by jdfreder** [comment]
This is great - actually exactly what I was hoping for.  I think, other than the dashboard PR, I was using this API somewhere else and was missing this functionality...  I think when I was writing the comm shim for ipywidgets.

**Comment by jdfreder** [comment]
Out of curiosity: in general, within jupyter-js-services, do you pass the full message through (like you're doing in this PR) or do you tend to only pass a subset of data that you thing is needed (like it was prior to this PR)?

**Comment by minrk** [comment]
:+1: We came to this same realization in the first implementation as well. It's better to pass whole messages around, rather than subsetting the content.
