### ISSUE TITLE
services seems to be ignoring baseUrl in getKernelSpecs

### ISSUE THREAD

**Issue by jdfreder** [jupyter/jupyter-js-services#73]
I have a webserver hosting my content on port 8080 and a notebook server running on 8888.

Running the following code:

```js
// Connect to the notebook webserver.
    getKernelSpecs('http://localhost:8888').then(kernelSpecs => {
        return startNewKernel({
            baseUrl: 'http://localhost:8888',
            wsUrl: 'ws://localhost:8888',
            name: kernelSpecs.default,
        });
    }).then(kernel => {});
```

yields 

```
GET http://localhost:8080/api/kernelspecs?1453312304541 404 (Not Found)
````

Correct me if I'm wrong, but it looks like jupyter-js-services is ignoring the base url I pass in to `getKernelSpecs`.  Instead it's using the window's current URL as a base.

See https://github.com/ipython/ipywidgets/pull/328

**Comment by jdfreder** [comment]
Aha, the API changed- why not release as a new major version?

**Comment by jdfreder** [comment]
For ref:

```js
// Connect to the notebook webserver.
    getKernelSpecs({baseUrl: 'http://localhost:8888'}).then(kernelSpecs => {
        return startNewKernel({
            baseUrl: 'http://localhost:8888',
            wsUrl: 'ws://localhost:8888',
            name: kernelSpecs.default,
        });
    }).then(kernel => {});
```

Works

**Comment by blink1073** [comment]
There is no major version yet, it is still considered alpha.  I did bump from 0.2 -> 0.3 for this change.

**Comment by jdfreder** [comment]
Sorry for the noise!  I should pay more attn to changes here
