### ISSUE TITLE
Starter from NodeJS

### ISSUE THREAD

**Issue by owen198** [jupyter/jupyter-js-services#86]
Hi:

I am a starter of NodeJS, I installed nodeJS/Jupiter Notebook and  jupyter-js-service successfully.
Is it possible to guild me to execute any usage example in README.md? 

Thanks,
Owen Lu

**Comment by blink1073** [comment]
Hi @owen198, if you follow these two sets of instructions, it should work for you (this is how we are running the test suite):

https://github.com/jupyter/jupyter-js-services#usage-from-nodejs
https://github.com/jupyter/jupyter-js-services#usage-examples

**Comment by owen198** [comment]
Hi @blink1073 ：thanks your help, I read those sections very carefully, but I cannot get how to execute any example from nodejs. I thought (1)it needs create a javascript file, and (2)paste any example into that file, then (3)use nodejs to execute it (such as "# node some-of-example.js"), am I correct?

**Comment by blink1073** [comment]
Yes, provided you have everything `npm install`ed correctly in the directory you are running the script from.  If you `npm install jupyter-js-services ws xmlhttprequest`, then run your script, that should be all you need.  If that doesn't work, you can put your script in a gist and along with any output from node and I can take a look.

**Comment by tristanz** [comment]
This may be silly, but one thing that is missing from the docs is how to actually start the jupyter server.  It's not 100% clear whether jupyter REST server is `jupyter notebook` with specific options or some other project or invocation.

**Comment by owen198** [comment]
Hi @blink1073 :
I tried install jupyter-js-services, ws and xmlhttprequest via npm, and I copied the code from usage example and pasted it to my site, an error message appeared after I executing the code:
# node ./Kernel.js 

/tmp/Kernel.js:1
(function (exports, require, module, __filename, __dirname) { import { XMLHttp
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

It seems a module "import" not found, how to deal with this issue?
`test`
Thanks,
Owen

**Comment by blink1073** [comment]
Hi @tristanz, thank you for the feedback, I will update the readme.

**Comment by blink1073** [comment]
@owen198, the code in the example is using EMCAScript 6 import syntax, which is not yet supported directly in `node` (coming in node v6 I hear).  The equivalent import would be something like `var xml = require('XMLHttpRequest')`.

**Comment by owen198** [comment]
Hi @blink1073: Thanks the feedback, I tried to execute an example to create a file, 

var ContentsManager = require ('jupyter-js-services');
var contents = new ContentsManager('http://140.92.25.58:8899');
contents.newUntitled("/foo", { type: "file", ext: "py" });

Somehow I got fail like this:

`# node ./Kernel.js`

/tmp/node_modules/jupyter-js-services/node_modules/phosphor-signaling/lib/index.js:254
var senderMap = new WeakMap();
                    ^
ReferenceError: WeakMap is not defined
    at Object.<anonymous> (/tmp/node_modules/jupyter-js-services/node_modules/phosphor-signaling/lib/index.js:254:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/node_modules/jupyter-js-services/lib/kernel.js:11:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Is anything wrong?

**Comment by blink1073** [comment]
Hmm, `WeakMap` should be included in node, you might have an older version, and may require the `weakmap` package.

**Comment by blink1073** [comment]
Yes, it looks like node 0.12+ is required for WeakMap.  This is the version specified in the readme.  I'm going to close this for inactivity, please feel free to reopen if you still can't get it working on node 0.12+.
